name: build-and-push-docker

on:
  push:
    branches:
      - main # 🎯 1. Déclencheur : on: push main:
      
env:
  DOCKER_IMAGE_NAME: Workflow Java
  DOCKER_HUB_USERNAME: xamflex6
  JAVA_VERSION: '17' 
  
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      # --- Étape 1 : Préparation et Compilation ---
      
      - name: Configuration du JDK ${{ env.JAVA_VERSION }} # 🎯 2. install jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          
      - name: Compilation avec Maven (ou Gradle) # 🎯 3. compiler le projet
        run: mvn clean package -DskipTests 

      # --- Étape 2 : Configuration Docker ---
      
      - name: Récupération du SHA court pour le tag de l'image
        id: docker_tag
        run: echo "SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT
      
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} 
          
      # --- Étape 3 & 4 : Build et Push ---
      
      - name: Construction des images Docker et Push # 🎯 4. Utiliser docker, Faire les images, 🎯 5. Push sur docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.docker_tag.outputs.SHA_SHORT }}
